# Generated by Django 3.2.4 on 2021-07-18 06:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210712_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='scan_image',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.file_path_encoder),
        ),
    ]
